version: '3.8'
services:
  oai_build:
    image: oai-base
    # container_name: ${DEV}_oai_ranwiser_build
    volumes:
      - ${ROOT_VOL}/openairinterface5g:${ROOT_VOL}/openairinterface5g
    entrypoint: "/bin/bash -c"
    command: >
        "cd ${ROOT_VOL}/openairinterface5g
        && source oaienv
        && cd cmake_targets
        && ./build_oai -w SIMU --gNB --nrUE --build-lib nrscope ${BUILD_CLEAN} |& tee build.log"
  oai_vnf:
    image: oai-base
    privileged: true
    # container_name: ${DEV}_oai_ranwiser_vnf0
    volumes:
      - ${ROOT_VOL}/openairinterface5g:${ROOT_VOL}/openairinterface5g
    environment:
      VNF_ADDR: ${VNF_ADDR}
      USERID: ${USERID}
      # NFAPI_TRACE_LEVEL: debug
    networks:
      rfsim5g-oai-public-net:
        ipv4_address: ${VNF_ADDR}
    entrypoint: "/bin/bash -c"
    command: >
        "cd ${ROOT_VOL}/openairinterface5g
        && source oaienv
        && cd ci-scripts/yaml_files/5g_rfsimulator_tdd_pvnf
        && python3 conf_generator.py -t vnf
        && chown -R ${USERID}:${USERID} ${ROOT_VOL}/openairinterface5g/ci-scripts/yaml_files/5g_rfsimulator_tdd_pvnf/conf
        && cd ${ROOT_VOL}/openairinterface5g/cmake_targets
        && ./ran_build/build/nr-softmodem ${R_W_SCOPE} -O ${ROOT_VOL}/openairinterface5g/ci-scripts/yaml_files/5g_rfsimulator_tdd_pvnf/conf/sCont.vnf.sa.band78.106prb.rfsim.conf --rfsim --sa -E --nfapi VNF |& tee vnf.log"
    healthcheck:
      test: /bin/bash -c "pgrep nr-softmodem"
      interval: 10s
      timeout: 5s
      retries: 5
  oai_pnf:
    image: oai-base
    privileged: true
    # container_name: ${DEV}_oai_ranwiser_pnf0
    volumes:
      - ${ROOT_VOL}/openairinterface5g:${ROOT_VOL}/openairinterface5g
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      RFSIMULATOR: server
      VNF_ADDR: ${VNF_ADDR}
      PNF_ADDR: ${PNF_ADDR}
      USERID: ${USERID}
      DISPLAY: ${DISPLAY}
      # NFAPI_TRACE_LEVEL: debug
    networks:
      rfsim5g-oai-public-net:
        ipv4_address: ${PNF_ADDR}
    entrypoint: "/bin/bash -c"
    command: >
        "cd ${ROOT_VOL}/openairinterface5g
        && source oaienv
        && cd ci-scripts/yaml_files/5g_rfsimulator_tdd_pvnf
        && python3 conf_generator.py -t pnf
        && chown -R ${USERID}:${USERID} ${ROOT_VOL}/openairinterface5g/ci-scripts/yaml_files/5g_rfsimulator_tdd_pvnf/conf
        && cd ${ROOT_VOL}/openairinterface5g/cmake_targets
        && ./ran_build/build/nr-softmodem ${R_W_SCOPE} -O ${ROOT_VOL}/openairinterface5g/ci-scripts/yaml_files/5g_rfsimulator_tdd_pvnf/conf/sCont.pnf.sa.band78.rfsim.conf --rfsim --sa -E --nfapi PNF |& tee pnf.log"
    depends_on:
      - oai_vnf
    healthcheck:
      test: /bin/bash -c "pgrep nr-softmodem"
      interval: 10s
      timeout: 5s
      retries: 5
  oai_ue:
    image: oai-base
    privileged: true
    # container_name: ${DEV}_oai_ranwiser_ue0
    volumes:
      - ${ROOT_VOL}/openairinterface5g:${ROOT_VOL}/openairinterface5g
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      # NFAPI_TRACE_LEVEL: debug
      RFSIMULATOR: ${PNF_ADDR}
      USERID: ${USERID}
      DISPLAY: ${DISPLAY}
    networks:
      rfsim5g-oai-public-net:
        ipv4_address: ${UE0_ADDR}
    # working_dir: ${ROOT_VOL}/openairinterface5g/cmake_targets/
    entrypoint: "/bin/bash -c"
    command: >
        "cd ${ROOT_VOL}/openairinterface5g
        && source oaienv
        && cd ci-scripts/yaml_files/5g_rfsimulator_tdd_pvnf
        && python3 conf_generator.py -t ue
        && chown -R ${USERID}:${USERID} ${ROOT_VOL}/openairinterface5g/ci-scripts/yaml_files/5g_rfsimulator_tdd_pvnf/conf
        && cd ${ROOT_VOL}/openairinterface5g/cmake_targets
        && ./ran_build/build/nr-uesoftmodem ${R_W_SCOPE} -O ${ROOT_VOL}/openairinterface5g/ci-scripts/yaml_files/5g_rfsimulator_tdd_pvnf/conf/sCont.ue.conf -C 3619200000 --rfsim --sa -E |& tee ue_pvnf.log"
    depends_on:
      - oai_pnf
networks:
  rfsim5g-oai-public-net:
    external: true
