version: '3'

services:
  gnb:
    image: oai-gnb:latest
    privileged: true
    container_name: gnodeb01-test
    environment:
      - USE_VOLUMED_CONF="yes"
      - USE_B2XX="yes"
      - USE_ADDITIONAL_OPTIONS="--sa -E --continuous-tx"
      - ENABLE_NETCONF=true
    volumes:
        - /dev:/dev
        - ./gNodeB/gnb.conf:/opt/oai-gnb/etc/mounted.conf
    healthcheck:
      # pgrep does NOT work
      test: /bin/bash -c "ps aux | grep -v grep | grep -c softmodem"
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - oam

networks:
  oam:
    external: true